### ISSUE TITLE
Working report （xiaoluoyuan）

### ISSUE THREAD

**Issue by elliott10** [openthos/system-analysis#86]
### openthos U盘使用版并保存用户data数据（new）

-  windows平台使用“Win32 Disk Imager ” 程序， Linux平台则使用”dd“命令，用于烧写img到U盘；
-  refind选择进入到U盘的LiveCD模式；
- 首次进入系统，程序会新分区并格式化本U盘新分区为ext2分区 以保存data数据，使用 parted /dev/sdx mkpart primary $start $end 
- 其中parted编译成android-x86可用版。

### 计划生成系统ISO镜像，其中整合包括.iso, efi支持legacy和uefi双中模式启动，类似ubuntu ISO

**Comment by elliott10** [comment]
### parted移植入android-x86系统命令

其中parted需要使用较老版本，如v1.9 ；
需要使用静态编译；
生成的静态parted放入openthos系统测试可用。

1. 配置参数：`./configure --enable-static  --disable-device-mapper  --disable-Werror`

2. 编译完成后查找"parted"程序的gcc生成命令行，在parted目录中`make -n`可查看得到：
`gcc -static -DBUILDINFO= -g -O2 -Wl,--as-needed -rdynamic -o parted_static parted-command.o parted-parted.o parted-strlist.o parted-ui.o parted-table.o  ../libparted/.libs/libparted.a -luuid -lreadline -ldl -ltinfo
 `
可知生成时使用的“**-static**”参数较关键。

也可参看wiki：
https://github.com/openthos/openthos/wiki/wimlib%E9%9D%99%E6%80%81%E9%93%BE%E6%8E%A5

**Comment by faxiang1230** [comment]
老板现在把周报集中管理在一起了,请更新到下面位置:
https://github.com/openthos/community-analysis/blob/master/weekly%20report/Weekly%20Report%20about%20System.md
中间实现过程请放在system-analysis中的code部分．

**Comment by elliott10** [comment]
初步完成了LiveCD的用户数据保存的代码编写；
测试效果并完善；
计划明天和wjx一起review讨论后提交。

**Comment by elliott10** [comment]
修复了几个小错误，与wjx一起review后，LiveCD用户数据保存的方案代码已经提交；
对于一个镜像中合并legacy,uefi启动的方式，结合使用grub与refind方式，细节测试当中。。。

**Comment by elliott10** [comment]
完成整理flash支持过程相关的文档；
调试代码服务器的提交脚本，发现修改了不少，导致更新github失败；

**Comment by elliott10** [comment]
**usb支持多分区**
现，只可自动弹出U盘的第一个分区 挂载/storage/usb0

相关代码：
base/services/usb/java/com/android/server/usb/UsbHostManager.java
base/services/core/jni/com_android_server_UsbHostManager.cpp

UsbSettingsManager.deviceAttached:741 

base/services/usb/java/com/android/server/usb/UsbSettingsManager.java +726 发送了广播ACTION_USB_DEVICE_ATTACHED

--> Vold机制
/system/vold
Vold 热插拔U盘自动增加/dev/block/vold/8:32之类的设备文件

vold挂载配置文件源码目录system/core/rootdir/etc
/system/vold/main.cpp:process_config

Volume.cpp:getDeviceNodes
handleDiskAdded()分区个数可正确识别  -->  
considered for volume usb1

**Comment by elliott10** [comment]
分析U盘挂载的VOLD；
其只挂载遇到的第一个可用分区；
重写相关函数，如获取挂载目录等函数

**Comment by elliott10** [comment]
对于linux启动logo修改并编写自动化脚本
需求分支包括openthos和一铭
 
---
详情：
https://github.com/elliott10/WorkingDocument/issues/1

**Comment by elliott10** [comment]
### 支持U盘多分区
涉及：native层**vold**, framework层**MountService**, 应用层**OtoFileManager**

目前已经实现的功能：vold底层的多分区挂载与卸载，并显示到OtoFileManager的图形列表中；

但对于点击分区卸载，图标不能即使消失;
对于应用层还需请教罗俊欢，对于列表的卸载OtoFileManager进行代码修改。

**Comment by elliott10** [comment]
OtoFileManager支持**U盘多分区**加载和卸载功能已测试较完善，
并跟wzx，wjx review代码，准备提交；

-----
发现新加的屏蔽字符输出，会导致不少启动时的shell无法正常实现该有的功能。

**Comment by elliott10** [comment]
向老师测试组再次报告OTO的自动更新又停了；
详细检测了github自动更新的部分，发现有些问题，包括之前子仓库的创建，oto仓库的本地与github的冲突等。

**Comment by elliott10** [comment]
协助dp进行一铭版的定制
https://github.com/elliott10/WorkingDocument/issues/1

---
Android Nougat 原生多窗口的调查研究
https://github.com/elliott10/WorkingDocument/issues/3

---
显卡的驱动支持和硬解码相关
https://github.com/elliott10/WorkingDocument/issues/4

**Comment by elliott10** [comment]
详细检测了github自动更新，梳理之前子仓库的创建，由于升级r38时，oto仓库的本地与github的冲突等

**Comment by faxiang1230** [comment]
我发现system/vold的更新没有反应上去.
后续我建议把multiwindow分支和aosp的tag分开
