### ISSUE TITLE
Working report 201704 (xiaoluoyuan)

### ISSUE THREAD

**Issue by openthos2016** [openthos/system-analysis#90]
### repo代码检测更新到github

**Comment by elliott10** [comment]
针对向老师测试那边多次反应的github repo自动更新停止的问题，
及 CWhuang提出的需要保持实验室内部repo与github repo代码的一致性自动检测要求。

前段时间：
整体升级repo到android-5.1.1_r38 ，之前wjx尝试升级过 但由于方式问题导致了不少更新的问题；
对github代码提交也作出检测；
自动化的完善；

涉及的文件：
/opt/git/lollipop-x86/.repo/manifest.xml 控制的整个repo的更新，以后project需再次升级到最新需进行修改；
lollipop-x86/manifest.git -b multiwindow 控制实验室repo代码的下载编译开发，新增oto等project时需进行修改；
github.com/openthos/OTO -b multiwindow控制外部github repo代码的下载编译，主要由实验室repo更新于此；

主要理清三者manifest关系，然后进行所需的更改，自动化的实现。

自动化实现脚本涉及185服务器：
checkupdate.sh
checkupdate.sh
checkupdate.sh

push2github.sh 设置好所需project到变量new_repo，运行时提供github用户名密码，将自动在github创建提供的project，并push到github。方式主要是调用github API。

proj_name2path.sh 把repo manifest的name转换成对应的path，有被checkupdate.sh调用。

**Comment by faxiang1230** [comment]
请将使用方法和实现概略整理到https://github.com/openthos/system-analysis/tree/master/maintain下

**Comment by elliott10** [comment]
20170413
协助chengang对android-x86的原生代码的获取及编译错误等解决，以进行MSoffice测试，错误由于编译时自动远程下载wl驱动包文件却下载错误；
Follow  CWHuang的硬解码部分，目前使用androidia的ffmpeg测试；
其他磁盘的自动挂载部分，真修改显示部分，在初始化的SdStorageFragment部分；

**Comment by elliott10** [comment]
20170414

分析修改filemanager的java部分代码

autoMount方案确定:
启动：左侧列表显示拓展分区，且不挂载，扫描显示已经挂载的拓展分区,右侧大框不显示拓展分区；
点击某个拓展分区，自动挂载显示弹出图标，并在右侧大框显示内容；

底层借用blkid 
/dev/block/sd[a-z][0-9] UUID="xxx" TYPE="ext4"
需注意区别自带分区与U盘
挂载于/storage/volumeX

**Comment by elliott10** [comment]
修改OtoFileManager的代码，增加fragment view
目前右键有些问题，请教之前处理过U盘类似问题的罗俊欢

**Comment by elliott10** [comment]
磁盘mount部分代码修改；
对陈鹏的vmware运行openthos的错误给予协助；
尝试androidia的硬解码支持；

**Comment by elliott10** [comment]
硬解码修改测试编译；
磁盘filemanager, mountservice与vold部分代码修改, 与王之旭讨论进度；
对陈工的repo仓库创建给予帮助；

**Comment by elliott10** [comment]
继续调app FileM 到 MountService 再到vold的bug

**Comment by elliott10** [comment]
接手xhl的window分区恢复工具代码，编译通过，并分析代码；
询问刘总关于该工具的具体需求，类似工具调研之；
协助ln解决p7zip的编译问题；

**Comment by openthos2016** [comment]
window分区恢复工具代码按照刘总需求修改；
修复jni的编译错误；

**Comment by openthos2016** [comment]
window分区恢复工具代码按照刘总需求修改；
修复jni的编译错误；

**Comment by elliott10** [comment]
window分区恢复工具代码按照刘总需求修改；
修复jni的编译错误；

**Comment by elliott10** [comment]
windows分区恢复工具，实机测试，并修改代码;
继续与wzx交涉关于该工具界面设计的协助，但他们组目前貌似比较忙无暇此协助

**Comment by elliott10** [comment]
windows分区恢复工具java部分代码修改；
dev.openthos.org网站失败修复；

**Comment by elliott10** [comment]
windows分区恢复工具
全面检测其功能的可用性，包括下载，恢复，增加分区自动扫描列表
