### ISSUE TITLE
Working report 201705- (xiaoluoyuan) 工作计划

### ISSUE THREAD

**Issue by elliott10** [openthos/system-analysis#93]
### 工作计划
1. windows分区恢复工具为装机的完善；
2. follow CW.Huang硬解码，需多跟踪实践代码（如7.1等的实现）；
2. 负责github与本地代码实时同步；
3. 与测试组的多沟通,并提供月反馈；
---
5. 学习加入multiwindow的bug解决，现微信聊天头部出现空白下沉问题，及其拉伸相关的问题尝试研究解决；

**Comment by elliott10** [comment]
https://github.com/openthos/community-analysis/tree/master/weekly%20report/work-progress

**Comment by elliott10** [comment]
windows分区恢复工具
合并WZX的界面代码;
重写网络下载class，之前的下载异常慢，原因未知；
编写efi备份函数；

**Comment by elliott10** [comment]
刘锋windows分区恢复工具新需求：

> 地址现在还无法确定，做个配置文件先用个测试地址放着吧，需要完成定义相关的格式规范（比如适用电脑型号、系统版本win10/win8/win7、系统次要版本比如build1703,1506等、大小、MD5校验值，语言，图标url等等）

根据刘总新需求修改代码；
研究qemu对android-x86 virgl 3d加速；

**Comment by elliott10** [comment]
对android-x86 7.1试验qemu virgl 3d加速运行，可运行，但有花屏、闪屏小bug；


对原生浏览器disable；
协助CMHuang集成fennec浏览器为系统应用；
集成windows系统恢复工具为系统应用；

github代码同步，并向老师沟通；

**Comment by openthos2016** [comment]
重现硬解码的移植过程，核心库为：intel-vaapi-driver， libva，android_external_ffmpeg，android_external_stagefright-plugins

目前我是在原android-x86情况下移植重现，目前编译通过。
